[package]
name = "example-contract"
version = "0.1.0"
edition = "2021"


[lib]
path = "contract.rs" 
crate-type = ["cdylib"]

[dependencies]
soroban-sdk = "20.0.0" 

[dev-dependencies]
soroban-sdk = { version = "20.0.0", features = ["testutils"] } 

[package.metadata.soroban]
contract = true